export enum StatusLivro {
  PENDENTE = 'PENDENTE',
  EMPRESTADO = 'EMPRESTADO',
  DEVOLVIDO = 'DEVOLVIDO',
  ATRASADO = 'ATRASADO',
  CANCELADO = 'CANCELADO',
  REVISAR = 'REVISAR',
  DISPONIVEL = 'DISPONIVEL',
}
