name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test -- --coverage

      - name: Build
        run: npm run build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
  terraform:
    name: 'Terraform Deploy'
    needs: build-and-test # Garante que o deploy só rode se os testes passarem
    runs-on: ubuntu-latest
    # Executa este job SOMENTE quando houver um push na branch main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      id-token: write # Necessário para interagir com o OIDC da AWS
      contents: read

    defaults:
      run:
        # Define o diretório onde os comandos do Terraform serão executados
        working-directory: terraform/envs/prod

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js (Necessário para o local-exec da Layer)
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Configurar Credenciais da AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        # O auto-approve é essencial em ambientes de CI/CD pois não há interação humana
        run: terraform apply -auto-approve tfplan
